# Generated by Django 5.1.2 on 2024-11-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_imageservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreport',
            name='text',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
