# Generated by Django 5.1.2 on 2024-12-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_category_description_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
